"""Initial migration.

Revision ID: 69e220a416ae
Revises: 
Create Date: 2022-11-04 14:05:16.782428

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '69e220a416ae'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('company',
    sa.Column('company_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('company_name', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('company_id')
    )
    op.create_table('platform',
    sa.Column('platform_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('platform_name', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('platform_id')
    )
    op.create_table('theme',
    sa.Column('theme_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('theme_name', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('theme_id')
    )
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('login', sa.String(length=50), nullable=True),
    sa.Column('name', sa.String(length=50), nullable=True),
    sa.Column('password', sa.String(length=80), nullable=True),
    sa.Column('admin', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('login')
    )
    op.create_table('text',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('text', sa.String(), nullable=True),
    sa.Column('date', sa.Date(), nullable=True),
    sa.Column('company_id', sa.Integer(), nullable=True),
    sa.Column('platform_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['company_id'], ['company.company_id'], ),
    sa.ForeignKeyConstraint(['platform_id'], ['platform.platform_id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('block_of_text',
    sa.Column('block_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('text_id', sa.Integer(), nullable=True),
    sa.Column('theme_id', sa.Integer(), nullable=True),
    sa.Column('block_text', sa.String(), nullable=True),
    sa.Column('sa_value', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['text_id'], ['text.id'], ),
    sa.ForeignKeyConstraint(['theme_id'], ['theme.theme_id'], ),
    sa.PrimaryKeyConstraint('block_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('block_of_text')
    op.drop_table('text')
    op.drop_table('user')
    op.drop_table('theme')
    op.drop_table('platform')
    op.drop_table('company')
    # ### end Alembic commands ###
